language: ruby
rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - ruby-head
script:
  - 'bundle exec rspec --color --format documentation'
notifications:
  recipients:
    - michele.bologna@gmail.com
    - marius.colacioiu@gmail.com

