---
http_interactions:
- request:
    method: get
    uri: http://mobile.viaggiatreno.it/vt_pax_internet/mobile/numero?lang=IT&numeroTreno=2566&tipoRicerca=numero
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 14 Jan 2016 16:02:09 GMT
      Content-Length:
      - '5767'
      Set-Cookie:
      - JSESSIONID=0000DQDIPlJO38p4RMN4EOdPYCo:16erma706; Path=/
      Expires:
      - Thu, 01 Dec 1994 16:00:00 GMT
      Cache-Control:
      - no-cache="set-cookie, set-cookie2"
      Content-Type:
      - text/html; charset=UTF-8
      Content-Language:
      - en-US
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        77u/DQoNCg0KPD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgi
        Pz4NCjwhRE9DVFlQRSBodG1sIFBVQkxJQyAiLS8vV0FQRk9SVU0vL0RURCBY
        SFRNTCBNb2JpbGUgMS4wLy9FTiIgImh0dHA6Ly93d3cud2FwZm9ydW0ub3Jn
        L0RURC94aHRtbC1tb2JpbGUxMC5kdGQiPg0KPGh0bWwgeG1sbnM9Imh0dHA6
        Ly93d3cudzMub3JnLzE5OTkveGh0bWwiPg0KCTxoZWFkPg0KCQk8bWV0YSBo
        dHRwLWVxdWl2PSJDb250ZW50LVR5cGUiIGNvbnRlbnQ9InRleHQvaHRtbDsg
        Y2hhcnNldD11dGYtOCIgLz4NCgkJPHRpdGxlPlNjaGVkYSB0cmVubzwvdGl0
        bGU+DQoJCTxsaW5rIGhyZWY9Ii92dF9wYXhfaW50ZXJuZXQvY3NzL21vYmls
        ZS5jc3MiIHJlbD0ic3R5bGVzaGVldCIgdHlwZT0idGV4dC9jc3MiIC8+DQoJ
        PC9oZWFkPg0KCTxib2R5Pg0KCQk8IS0tIFRFU1RBVEEgLS0+DQoJCTxkaXY+
        DQoNCjxkaXYgY2xhc3M9InRlc3RhdGFfcmVkIj4NCgkNCjwvZGl2PiA8L2Rp
        dj4NCg0KCQkNCgkJCQ0KCQkJDQoJCQkJPCEtLSBUSVRPTE8gLS0+DQoJCQkJ
        PGgxPlJFRyAyNTY2PC9oMT4NCiAgICAgICAgICAgICAgICA8IS0tIFNPVFRP
        VElUT0xPIFBFUiBQUk9WVkVESU1FTlRJIC0tPg0KICAgICAgICAgICAgICAg
        IA0KICAgICAgICAgICAgICAgIDwhLS0gT1JJR0lORSAtLT4NCgkJCQk8ZGl2
        IGNsYXNzPSJjb3Jwb2NlbnRyYWxlIj4NCiAgICAgICAgICAgICAgICAgICAg
        PGgyPk1JTEFOTyBDRU5UUkFMRTwvaDI+DQoJCQkJCTxwPlBhcnRlbnphIHBy
        b2dyYW1tYXRhICAgOjxici8+DQogICAgICAgICAgICAgICAgICAgICAgICA8
        c3Ryb25nPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIA0KICAgICAg
        ICAgICAgICAgICAgICAgICAgICAgICAgICAxNjoyMA0KICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAgICAgICAg
        IA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICANCiAgICAgICAg
        ICAgICAgICAgICAgICAgICAgICANCiAgICAgICAgICAgICAgICAgICAgICAg
        IDwvc3Ryb25nPg0KCQkJCQk8L3A+DQoJCQkJCTxwPlBhcnRlbnphIGVmZmV0
        dGl2YTo8YnIvPg0KCQkJCQk8c3Ryb25nPjE2OjIyPC9zdHJvbmc+DQoJCQkJ
        CTwvcD4NCiAgICAgICAgICAgICAgICAgICAgQmluYXJpbw0KICAgICAgICAg
        ICAgICAgICAgICBQcmV2aXN0bzo8YnI+DQogICAgICAgICAgICAgICAgICAg
        IA0KICAgICAgICAgICAgICAgICAgICAgICAgDQogICAgICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgICANCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
        IA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgDQog
        ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA0K
        ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
        ICAgNSAgICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgICAgICANCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAN
        CiAgICAgICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAg
        ICAgICAgDQogICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAg
        ICAgICA8YnI+DQogICAgICAgICAgICAgICAgICAgIEJpbmFyaW8NCiAgICAg
        ICAgICAgICAgICAgICAgUmVhbGU6PGJyPg0KICAgICAgICAgICAgICAgICAg
        ICANCiAgICAgICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAg
        ICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
        ICANCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxzdHJv
        bmc+NDwvc3Ryb25nPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
        ICANCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgDQogICAgICAg
        ICAgICAgICAgICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgICAgICAg
        ICANCiAgICAgICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAg
        ICAgICANCiAgICAgICAgICAgICAgICA8L2Rpdj4NCg0KCQkJCTwhLS0gVUxU
        SU1BIEZFUk1BVEEgLS0+DQoJCQkJDQoJCQkJCTxkaXYgY2xhc3M9ImV2aWRl
        bnppYXRvIj4NCiAgICAgICAgICAgICAgICAgICAgICAgIFVsdGltYSBmZXJt
        YXRhIGVmZmV0dHVhdGE6DQogICAgICAgICAgICAgICAgICAgIDwvZGl2Pg0K
        CQkJCQk8ZGl2IGNsYXNzPSJjb3Jwb2NlbnRyYWxlIj4NCgkJCQkJCTxoMj5M
        RUNDTzwvaDI+DQoJCQkJCQk8cD5BcnJpdm8gUHJvZ3JhbW1hdG86PGJyLz4N
        CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8c3Ryb25nPg0KICAgICAg
        ICAgICAgICAgICAgICAgICAgICAgICAgICANCiAgICAgICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgICAgIDE2OjU5DQogICAgICAgICAgICAgICAgICAg
        ICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
        ICANCiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L3N0cm9uZz4NCgkJ
        CQkJCTwvcD4NCgkJCQkJCTxwPg0KICAgICAgICAgICAgICAgICAgICAgICAg
        ICAgIEFycml2byBlZmZldHRpdm86PGJyLz4NCgkJCQkJCSAgICA8c3Ryb25n
        Pg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICANCiAgICAgICAg
        ICAgICAgICAgICAgICAgICAgICAgICAgICAgIDE2OjU4DQogICAgICAgICAg
        ICAgICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgIDwvc3Ryb25nPg0KCQkJCQkJPC9wPg0KCQkJCQk8L2Rpdj4NCgkJ
        CQkNCg0KCQkJCTwhLS0gTElOSyBERVRUQUdMSU8gRkVSTUFURSAtLT4NCgkJ
        CQkNCgkJCQkJPGRpdiBjbGFzcz0iZXZpZGVuemlhdG8iPg0KICAgICAgICAg
        ICAgICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgICAgICAgICA8YSBo
        cmVmPSIvdnRfcGF4X2ludGVybmV0L21vYmlsZS9zY2hlZGE/ZGV0dGFnbGlv
        PXZpc3VhbGl6emEmbnVtZXJvVHJlbm89MjU2NiZjb2RMb2NPcmlnPSZ0aXBv
        UmljZXJjYT1udW1lcm8mbGFuZz1JVCI+wrsgVmVkaSBkZXR0YWdsaW8gZmVy
        bWF0ZTwvYT4NCgkJCQkJPC9kaXY+DQoJCQkJDQoNCiAgICAgICAgICAgICAg
        ICA8IS0tIERFU1RJTkFaSU9ORSAtLT4NCgkJCQk8ZGl2IGNsYXNzPSJjb3Jw
        b2NlbnRyYWxlIj4NCgkJCQkJPGgyPlRJUkFOTzwvaDI+DQoJCQkJCTxwPkFy
        cml2byBQcm9ncmFtbWF0bzo8YnIvPg0KCQkJCQkgICAgPHN0cm9uZz4NCiAg
        ICAgICAgICAgICAgICAgICAgICAgICAgICANCiAgICAgICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgMTg6NTINCiAgICAgICAgICAgICAgICAgICAgICAg
        ICAgICANCiAgICAgICAgICAgICAgICAgICAgICAgICAgICANCiAgICAgICAg
        ICAgICAgICAgICAgICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgICAg
        ICAgICAgICAgDQogICAgICAgICAgICAgICAgICAgICAgICA8L3N0cm9uZz4N
        CgkJCQkJPC9wPg0KCQkJCQk8cD4NCgkJCQkJDQoJCQkJCQkNCgkJCQkJCQ0K
        CQkJCQkJCUFycml2byBwcmV2aXN0bzo8YnIvPg0KCQkJCQkJCTxzdHJvbmc+
        MTg6NTI8L3N0cm9uZz4NCgkJCQkJCQ0KCQkJCQkNCgkJCQkJPC9wPg0KDQog
        ICAgICAgICAgICAgICAgICAgIEJpbmFyaW8NCiAgICAgICAgICAgICAgICAg
        ICAgUHJldmlzdG86PGJyPg0KICAgICAgICAgICAgICAgICAgICANCiAgICAg
        ICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAgICAg
        DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgDQogICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgIDEgICAgICAgICAgICAgIA0KICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgICAgICAgICAg
        ICAgDQogICAgICAgICAgICAgICAgICAgICAgICANCiAgICAgICAgICAgICAg
        ICAgICAgDQogICAgICAgICAgICAgICAgICAgIDxicj4NCiAgICAgICAgICAg
        ICAgICAgICAgQmluYXJpbw0KICAgICAgICAgICAgICAgICAgICBSZWFsZTo8
        YnI+DQogICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAg
        ICAgICAgDQogICAgICAgICAgICAgICAgICAgICAgICANCiAgICAgICAgICAg
        ICAgICAgICAgICAgICAgIC0tDQogICAgICAgICAgICAgICAgICAgICAgICAN
        CiAgICAgICAgICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgPC9kaXY+
        DQoJCQ0KCQkJCTwhLS0gU0lUVUFaSU9ORSAtLT4NCgkJCQk8ZGl2ICBjbGFz
        cz0iZXZpZGVuemlhdG8iPjxzdHJvbmc+DQoJCQkJSWwgdHJlbm8NCgkJCQkN
        CgkJCQkJDQoJCQkJCQ0KCQkJCQkNCgkJCQkJCXZpYWdnaWENCgkJCQkJCQ0K
        CQkJCQkJCQ0KCQkJCQkJCWNvbiAxIG1pbnV0aSBkaSBhbnRpY2lwbw0KCQkJ
        CQkJCQ0KCQkJCQkJDQoJCQkJCQ0KCQkJCQ0KICAgICAgICAgICAgICAgIDxi
        cj4NCiAgICAgICAgICAgICAgICAgPCEtLWM6aWYgdGVzdD0iJHshZW1wdHkg
        YW5kYW1lbnRvLnN0YXppb25lVWx0aW1vUmlsZXZhbWVudG8gJiYgISBlbXB0
        eSBhbmRhbWVudG8ub3JhVWx0aW1vUmlsZXZhbWVudG8gJiYgZW1wdHkgYXJy
        aXZvLmVmZmV0dGl2YX0iLS0+DQogICAgICAgICAgICAgICAgDQogICAgICAg
        ICAgICAgICAgICAgIFVsdGltbyByaWxldmFtZW50byBhIExFQ0NPIGFsbGUg
        b3JlIDE2OjU4DQogICAgICAgICAgICAgICAgDQoNCiAgICAgICAgICAgICAg
        ICA8L3N0cm9uZz48YnI+DQogICAgICAgICAgICAgICAgPC9kaXY+DQoJCQkN
        CgkJDQoJCQ0KCQk8IS0tIEZPT1RFUiArIExJTksgLS0+DQoJCTxkaXYgaWQ9
        ImZvb3RlciI+DQoJCQkNCgkJCQkNCgkJCQkNCgkJCQkJPGEgaHJlZj0iL3Z0
        X3BheF9pbnRlcm5ldC9tb2JpbGUvbnVtZXJvP2xhbmc9SVQiPsK7IE51b3Zh
        IHJpY2VyY2EgPC9hPjxici8+DQogICAgICAgICAgICAgICAgICAgIDxhIGhy
        ZWY9Ii92dF9wYXhfaW50ZXJuZXQvbW9iaWxlL3N0YXppb25lP2xhbmc9SVQi
        PsK7IENlcmNhIHBlciBzdGF6aW9uZTwvYT4NCiAgICAgICAgICAgICAgICAg
        ICAgPGEgaHJlZj0iL3Z0X3BheF9pbnRlcm5ldC9tb2JpbGUvdHJhZ2l0dG8/
        bGFuZz1JVCI+wrsgQ2VyY2EgcGVyIGRhdGkgZGkgdmlhZ2dpbzwvYT48YnIv
        Pg0KICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgIA0KICAgICAg
        ICAgICAgDQogICAgICAgICAgICA8YnI+DQoNCiAgICAgICAgICAgIDxwPjxp
        bWcgc3JjPSIvdnRfcGF4X2ludGVybmV0L2ltYWdlcy9pY29uYVJpY2VyY2Eu
        cG5nIiBzdHlsZT0idmVydGljYWwtYWxpZ246IG1pZGRsZTsiLz4NCiAgICAg
        ICAgICAgICAgICA8YSBocmVmPSIvdnRfcGF4X2ludGVybmV0L21vYmlsZS9w
        cm9ncmFtbWF0bz9sYW5nPUlUIj5PcmFyaW8gVHJlbmk8L2E+DQogICAgICAg
        ICAgICA8L3A+DQogICAgICAgICAgICA8cCBpZD0iY29weW5vdGUiPkNvcHly
        aWdodCBUcmVuaXRhbGlhIFMucC5BLiAyMDA2LjxiciAvPlR1dHRpIGkgZGly
        aXR0aSByaXNlcnZhdGkuPC9wPg0KCQk8L2Rpdj4NCg0KCTwvYm9keT4NCjwv
        aHRtbD4NCg==
    http_version: 
  recorded_at: Thu, 14 Jan 2016 16:02:09 GMT
recorded_with: VCR 3.0.1
