---
http_interactions:
- request:
    method: get
    uri: http://mobile.viaggiatreno.it/vt_pax_internet/mobile/numero?lang=IT&numeroTreno=20241&tipoRicerca=numero
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - ! '*/*'
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: !binary |-
        T0s=
    headers:
      !binary "RGF0ZQ==":
      - !binary |-
        RnJpLCAyNSBBcHIgMjAxNCAxODozMzozOSBHTVQ=
      !binary "Q29udGVudC1MZW5ndGg=":
      - !binary |-
        NjIyMg==
      !binary "U2V0LUNvb2tpZQ==":
      - !binary |-
        SlNFU1NJT05JRD0wMDAwdktCYWF6dDdNTHc5aG9RamlfWnY2a1o6MTZuNzhz
        bWtmOyBQYXRoPS8=
      !binary "RXhwaXJlcw==":
      - !binary |-
        VGh1LCAwMSBEZWMgMTk5NCAxNjowMDowMCBHTVQ=
      !binary "Q2FjaGUtQ29udHJvbA==":
      - !binary |-
        bm8tY2FjaGU9InNldC1jb29raWUsIHNldC1jb29raWUyIg==
      !binary "Q29udGVudC1UeXBl":
      - !binary |-
        dGV4dC9odG1sOyBjaGFyc2V0PVVURi04
      !binary "Q29udGVudC1MYW5ndWFnZQ==":
      - !binary |-
        ZW4tVVM=
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        77u/DQoNCg0KPD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgi
        Pz4NCjwhRE9DVFlQRSBodG1sIFBVQkxJQyAiLS8vV0FQRk9SVU0vL0RURCBY
        SFRNTCBNb2JpbGUgMS4wLy9FTiIgImh0dHA6Ly93d3cud2FwZm9ydW0ub3Jn
        L0RURC94aHRtbC1tb2JpbGUxMC5kdGQiPg0KPGh0bWwgeG1sbnM9Imh0dHA6
        Ly93d3cudzMub3JnLzE5OTkveGh0bWwiPg0KCTxoZWFkPg0KCQk8bWV0YSBo
        dHRwLWVxdWl2PSJDb250ZW50LVR5cGUiIGNvbnRlbnQ9InRleHQvaHRtbDsg
        Y2hhcnNldD11dGYtOCIgLz4NCgkJPHRpdGxlPlNjaGVkYSB0cmVubzwvdGl0
        bGU+DQoJCTxsaW5rIGhyZWY9Ii92dF9wYXhfaW50ZXJuZXQvY3NzL21vYmls
        ZS5jc3MiIHJlbD0ic3R5bGVzaGVldCIgdHlwZT0idGV4dC9jc3MiIC8+DQoJ
        PC9oZWFkPg0KCTxib2R5Pg0KCQk8IS0tIFRFU1RBVEEgLS0+DQoJCTxkaXY+
        DQoNCjx0YWJsZSBzdHlsZT0id2lkdGg6MTAwJTsgaGVpZ2h0OjIycHgiIGNl
        bGxwYWRkaW5nPScwJyBjZWxsc3BhY2luZz0nMCcgY2xhc3M9J3Rlc3RhdGFf
        cmVkJyBib3JkZXI9JzAnPg0KDQogICAgPHRyIGJnY29sb3I9JyNGRkZGRkYn
        IHN0eWxlPSJoZWlnaHQ6MXB4Ij4NCiAgICAgICAgPHRkIHN0eWxlPSJ3aWR0
        aDoxMjZweCIgYmdjb2xvcj0nI0ZGRkZGRic+PC90ZD4NCiAgICAgICAgPHRk
        IGJnY29sb3I9JyNGRkZGRkYnPjwvdGQ+DQogICAgPC90cj4NCg0KICAgIDx0
        ciBzdHlsZT0id2lkdGg6MTAwJTsgaGVpZ2h0OjIycHgiPg0KICAgICAgICA8
        dGQgc3R5bGU9IndpZHRoOjEyNnB4IiBhbGlnbj0nbGVmdCc+DQogICAgICAg
        ICAgICA8aW1nIHNyYz0iL3Z0X3BheF9pbnRlcm5ldC9pbWFnZXMvaGVhZGVy
        X21vYmlsZV9yZWQuZ2lmIiB0aXRsZT0iVmlhZ2dpYSBUcmVubyIgYWx0PSIi
        IC8+DQogICAgICAgIDwvdGQ+DQogICAgICAgIDx0ZCBzdHlsZT0id2lkdGg6
        MTAwJSIgYWxpZ249J3JpZ2h0Jz4NCiAgICAgICAgICAgIDxpbWcgYWxpZ249
        J3JpZ2h0JyBzcmM9Ii92dF9wYXhfaW50ZXJuZXQvaW1hZ2VzL2hlYWRlcl9t
        b2JpbGVfY2xvY2suZ2lmIiB0aXRsZT0iVmlhZ2dpYSBUcmVubyIgYWx0PSIi
        IC8+DQogICAgICAgIDwvdGQ+DQogICAgPC90cj4NCg0KICAgIDx0ciBiZ2Nv
        bG9yPScjRkZGRkZGJyBzdHlsZT0iaGVpZ2h0OjFweCI+DQogICAgICAgIDx0
        ZCBzdHlsZT0id2lkdGg6MTI2cHgiIGJnY29sb3I9JyNGRkZGRkYnPjwvdGQ+
        DQogICAgICAgIDx0ZCBiZ2NvbG9yPScjRkZGRkZGJz48L3RkPg0KICAgIDwv
        dHI+DQoNCjwvdGFibGU+DQoNCjwvZGl2Pg0KDQoJCQ0KCQkJDQoJCQkNCgkJ
        CQk8IS0tIFRJVE9MTyAtLT4NCgkJCQk8aDE+UkVHIDIwMjQxPC9oMT4NCiAg
        ICAgICAgICAgICAgICA8IS0tIFNPVFRPVElUT0xPIFBFUiBQUk9WVkVESU1F
        TlRJIC0tPg0KICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgIDwh
        LS0gT1JJR0lORSAtLT4NCgkJCQk8ZGl2IGNsYXNzPSJjb3Jwb2NlbnRyYWxl
        Ij4NCiAgICAgICAgICAgICAgICAgICAgPGgyPkRPTU9ET1NTT0xBPC9oMj4N
        CgkJCQkJPHA+UGFydGVuemEgcHJvZ3JhbW1hdGEgICA6PGJyLz4NCiAgICAg
        ICAgICAgICAgICAgICAgICAgIDxzdHJvbmc+DQogICAgICAgICAgICAgICAg
        ICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
        IDE4OjEwDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgDQogICAgICAg
        ICAgICAgICAgICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIA0KICAg
        ICAgICAgICAgICAgICAgICAgICAgPC9zdHJvbmc+DQoJCQkJCTwvcD4NCgkJ
        CQkJPHA+UGFydGVuemEgZWZmZXR0aXZhOjxici8+DQoJCQkJCTxzdHJvbmc+
        MTg6MTE8L3N0cm9uZz4NCgkJCQkJPC9wPg0KICAgICAgICAgICAgICAgICAg
        ICBCaW5hcmlvDQogICAgICAgICAgICAgICAgICAgIFByZXZpc3RvOjxicj4N
        CiAgICAgICAgICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgICAgICAg
        ICANCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICANCiAgICAgICAg
        ICAgICAgICAgICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgICANCiAgICAgICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgICAgICAgICAzICAgICAgICAgICAgICANCiAgICAg
        ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgDQogICAg
        ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICANCiAg
        ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICANCiAgICAg
        ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAgICAg
        DQogICAgICAgICAgICAgICAgICAgICAgICANCiAgICAgICAgICAgICAgICAg
        ICAgDQogICAgICAgICAgICAgICAgICAgIDxicj4NCiAgICAgICAgICAgICAg
        ICAgICAgQmluYXJpbw0KICAgICAgICAgICAgICAgICAgICBSZWFsZTo8YnI+
        DQogICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAg
        ICAgDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgDQogICAgICAgICAg
        ICAgICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgPHN0cm9uZz4zPC9zdHJvbmc+DQogICAgICAgICAg
        ICAgICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgICAgICANCiAgICAgICAgICAgICAgICAgICAgICAgICAgICANCiAg
        ICAgICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAg
        ICAgDQogICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgIDwv
        ZGl2Pg0KDQoJCQkJPCEtLSBVTFRJTUEgRkVSTUFUQSAtLT4NCgkJCQkNCg0K
        CQkJCTwhLS0gTElOSyBERVRUQUdMSU8gRkVSTUFURSAtLT4NCgkJCQkNCgkJ
        CQkJPGRpdiBjbGFzcz0iZXZpZGVuemlhdG8iPg0KICAgICAgICAgICAgICAg
        ICAgICAgICAgDQogICAgICAgICAgICAgICAgICAgICAgICA8YSBocmVmPSIv
        dnRfcGF4X2ludGVybmV0L21vYmlsZS9zY2hlZGE/ZGV0dGFnbGlvPXZpc3Vh
        bGl6emEmbnVtZXJvVHJlbm89MjAyNDEmY29kTG9jT3JpZz0mdGlwb1JpY2Vy
        Y2E9bnVtZXJvJmxhbmc9SVQiPsK7IFZlZGkgZGV0dGFnbGlvIGZlcm1hdGU8
        L2E+DQoJCQkJCTwvZGl2Pg0KCQkJCQ0KDQogICAgICAgICAgICAgICAgPCEt
        LSBERVNUSU5BWklPTkUgLS0+DQoJCQkJPGRpdiBjbGFzcz0iY29ycG9jZW50
        cmFsZSI+DQoJCQkJCTxoMj5NSUxBTk8gUE9SVEEgR0FSSUJBTERJPC9oMj4N
        CgkJCQkJPHA+QXJyaXZvIFByb2dyYW1tYXRvOjxici8+DQoJCQkJCSAgICA8
        c3Ryb25nPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIA0KICAgICAg
        ICAgICAgICAgICAgICAgICAgICAgICAgICAyMDoxMw0KICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAgICAgICAg
        IA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICANCiAgICAgICAg
        ICAgICAgICAgICAgICAgICAgICANCiAgICAgICAgICAgICAgICAgICAgICAg
        IDwvc3Ryb25nPg0KCQkJCQk8L3A+DQoJCQkJCTxwPg0KCQkJCQkNCgkJCQkJ
        CQ0KCQkJCQkJCUFycml2byBlZmZldHRpdm86PGJyLz4NCgkJCQkJCQk8c3Ry
        b25nPjIwOjE1PC9zdHJvbmc+DQoJCQkJCQkNCgkJCQkJCQ0KCQkJCQkNCgkJ
        CQkJPC9wPg0KDQogICAgICAgICAgICAgICAgICAgIEJpbmFyaW8NCiAgICAg
        ICAgICAgICAgICAgICAgUHJldmlzdG86PGJyPg0KICAgICAgICAgICAgICAg
        ICAgICANCiAgICAgICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
        ICAgICANCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
        IA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
        ICANCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgIDQgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgICAgICAgICANCiAgICAgICAgICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgICAgICAgICAgICAg
        ICAgDQogICAgICAgICAgICAgICAgICAgICAgICANCiAgICAgICAgICAgICAg
        ICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICANCiAgICAgICAgICAg
        ICAgICAgICAgPGJyPg0KICAgICAgICAgICAgICAgICAgICBCaW5hcmlvDQog
        ICAgICAgICAgICAgICAgICAgIFJlYWxlOjxicj4NCiAgICAgICAgICAgICAg
        ICAgICAgDQogICAgICAgICAgICAgICAgICAgICAgICANCiAgICAgICAgICAg
        ICAgICAgICAgICAgICAgICANCiAgICAgICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8
        c3Ryb25nPjQ8L3N0cm9uZz4NCiAgICAgICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA0KICAg
        ICAgICAgICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAg
        ICAgICAgDQogICAgICAgICAgICAgICAgICAgICAgICANCiAgICAgICAgICAg
        ICAgICAgICAgDQogICAgICAgICAgICAgICAgPC9kaXY+DQoJCQ0KCQkJCTwh
        LS0gU0lUVUFaSU9ORSAtLT4NCgkJCQk8ZGl2ICBjbGFzcz0iZXZpZGVuemlh
        dG8iPjxzdHJvbmc+DQoJCQkJSWwgdHJlbm8NCgkJCQkNCgkJCQkJDQoJCQkJ
        CQ0KCQkJCQkJZSYjMDM5OyBhcnJpdmF0bw0KCQkJCQkJDQoJCQkJCQkJY29u
        IDIgbWludXRpIGRpIHJpdGFyZG8NCgkJCQkJCQkNCgkJCQkJCQkNCgkJCQkJ
        CQ0KCQkJCQkNCgkJCQkJDQoJCQkJDQogICAgICAgICAgICAgICAgPGJyPg0K
        ICAgICAgICAgICAgICAgICA8IS0tYzppZiB0ZXN0PSIkeyFlbXB0eSBhbmRh
        bWVudG8uc3RhemlvbmVVbHRpbW9SaWxldmFtZW50byAmJiAhIGVtcHR5IGFu
        ZGFtZW50by5vcmFVbHRpbW9SaWxldmFtZW50byAmJiBlbXB0eSBhcnJpdm8u
        ZWZmZXR0aXZhfSItLT4NCiAgICAgICAgICAgICAgICANCg0KICAgICAgICAg
        ICAgICAgIDwvc3Ryb25nPjxicj4NCiAgICAgICAgICAgICAgICA8L2Rpdj4N
        CgkJCQ0KCQkNCgkJDQoJCTwhLS0gRk9PVEVSICsgTElOSyAtLT4NCgkJPGRp
        diBpZD0iZm9vdGVyIj4NCgkJCQ0KCQkJCQ0KCQkJCQ0KCQkJCQk8YSBocmVm
        PSIvdnRfcGF4X2ludGVybmV0L21vYmlsZS9udW1lcm8/bGFuZz1JVCI+wrsg
        TnVvdmEgcmljZXJjYSA8L2E+PGJyLz4NCiAgICAgICAgICAgICAgICAgICAg
        PGEgaHJlZj0iL3Z0X3BheF9pbnRlcm5ldC9tb2JpbGUvc3RhemlvbmU/bGFu
        Zz1JVCI+wrsgQ2VyY2EgcGVyIHN0YXppb25lPC9hPg0KICAgICAgICAgICAg
        ICAgICAgICA8YSBocmVmPSIvdnRfcGF4X2ludGVybmV0L21vYmlsZS90cmFn
        aXR0bz9sYW5nPUlUIj7CuyBDZXJjYSBwZXIgZGF0aSBkaSB2aWFnZ2lvPC9h
        Pjxici8+DQogICAgICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgDQog
        ICAgICAgICAgICANCiAgICAgICAgICAgIDxicj4NCg0KICAgICAgICAgICAg
        PHA+PGltZyBzcmM9Ii92dF9wYXhfaW50ZXJuZXQvaW1hZ2VzL2ljb25hUmlj
        ZXJjYS5wbmciIHN0eWxlPSJ2ZXJ0aWNhbC1hbGlnbjogbWlkZGxlOyIvPg0K
        ICAgICAgICAgICAgICAgIDxhIGhyZWY9Ii92dF9wYXhfaW50ZXJuZXQvbW9i
        aWxlL3Byb2dyYW1tYXRvP2xhbmc9SVQiPk9yYXJpbyBUcmVuaTwvYT4NCiAg
        ICAgICAgICAgIDwvcD4NCiAgICAgICAgICAgIDxwIGlkPSJjb3B5bm90ZSI+
        Q29weXJpZ2h0IFRyZW5pdGFsaWEgUy5wLkEuIDIwMDYuPGJyIC8+VHV0dGkg
        aSBkaXJpdHRpIHJpc2VydmF0aS48L3A+DQoJCTwvZGl2Pg0KDQoJPC9ib2R5
        Pg0KPC9odG1sPg0K
    http_version: 
  recorded_at: Fri, 25 Apr 2014 18:33:39 GMT
recorded_with: VCR 2.9.0
