---
http_interactions:
- request:
    method: get
    uri: http://mobile.viaggiatreno.it/vt_pax_internet/mobile/numero?lang=IT&numeroTreno=2572&tipoRicerca=numero
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 14 Jan 2016 15:34:06 GMT
      Content-Length:
      - '4479'
      Set-Cookie:
      - JSESSIONID=0000YeyUUrp40eQ07VKtRcn7Ayc:16n78t41a; Path=/
      Expires:
      - Thu, 01 Dec 1994 16:00:00 GMT
      Cache-Control:
      - no-cache="set-cookie, set-cookie2"
      Content-Type:
      - text/html; charset=UTF-8
      Content-Language:
      - en-US
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        77u/DQoNCg0KPD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgi
        Pz4NCjwhRE9DVFlQRSBodG1sIFBVQkxJQyAiLS8vV0FQRk9SVU0vL0RURCBY
        SFRNTCBNb2JpbGUgMS4wLy9FTiIgImh0dHA6Ly93d3cud2FwZm9ydW0ub3Jn
        L0RURC94aHRtbC1tb2JpbGUxMC5kdGQiPg0KPGh0bWwgeG1sbnM9Imh0dHA6
        Ly93d3cudzMub3JnLzE5OTkveGh0bWwiPg0KCTxoZWFkPg0KCQk8bWV0YSBo
        dHRwLWVxdWl2PSJDb250ZW50LVR5cGUiIGNvbnRlbnQ9InRleHQvaHRtbDsg
        Y2hhcnNldD11dGYtOCIgLz4NCgkJPHRpdGxlPlNjaGVkYSB0cmVubzwvdGl0
        bGU+DQoJCTxsaW5rIGhyZWY9Ii92dF9wYXhfaW50ZXJuZXQvY3NzL21vYmls
        ZS5jc3MiIHJlbD0ic3R5bGVzaGVldCIgdHlwZT0idGV4dC9jc3MiIC8+DQoJ
        PC9oZWFkPg0KCTxib2R5Pg0KCQk8IS0tIFRFU1RBVEEgLS0+DQoJCTxkaXY+
        DQoNCjxkaXYgY2xhc3M9InRlc3RhdGFfcmVkIj4NCgkNCjwvZGl2PiA8L2Rp
        dj4NCg0KCQkNCgkJCQ0KCQkJDQoJCQkJPCEtLSBUSVRPTE8gLS0+DQoJCQkJ
        PGgxPlJFRyAyNTcyPC9oMT4NCiAgICAgICAgICAgICAgICA8IS0tIFNPVFRP
        VElUT0xPIFBFUiBQUk9WVkVESU1FTlRJIC0tPg0KICAgICAgICAgICAgICAg
        IA0KICAgICAgICAgICAgICAgIDwhLS0gT1JJR0lORSAtLT4NCgkJCQk8ZGl2
        IGNsYXNzPSJjb3Jwb2NlbnRyYWxlIj4NCiAgICAgICAgICAgICAgICAgICAg
        PGgyPk1JTEFOTyBDRU5UUkFMRTwvaDI+DQoJCQkJCTxwPlBhcnRlbnphIHBy
        b2dyYW1tYXRhICAgOjxici8+DQogICAgICAgICAgICAgICAgICAgICAgICA8
        c3Ryb25nPg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIA0KICAgICAg
        ICAgICAgICAgICAgICAgICAgICAgICAgICAxODoyMA0KICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAgICAgICAg
        IA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICANCiAgICAgICAg
        ICAgICAgICAgICAgICAgICAgICANCiAgICAgICAgICAgICAgICAgICAgICAg
        IDwvc3Ryb25nPg0KCQkJCQk8L3A+DQoJCQkJCTxwPlBhcnRlbnphIGVmZmV0
        dGl2YTo8YnIvPg0KCQkJCQk8c3Ryb25nPjwvc3Ryb25nPg0KCQkJCQk8L3A+
        DQogICAgICAgICAgICAgICAgICAgIEJpbmFyaW8NCiAgICAgICAgICAgICAg
        ICAgICAgUHJldmlzdG86PGJyPg0KICAgICAgICAgICAgICAgICAgICANCiAg
        ICAgICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAg
        ICAgDQogICAgICAgICAgICAgICAgICAgICAgICAgICANCiAgICAgICAgICAg
        ICAgICAgICAgICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgICAgICAgICA1ICAgICAgICAgICAgICANCiAgICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgICANCiAgICAgICAgICAgICAgICAgICAgICAgICAgICANCiAgICAg
        ICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICANCiAg
        ICAgICAgICAgICAgICAgICAgPGJyPg0KICAgICAgICAgICAgICAgICAgICBC
        aW5hcmlvDQogICAgICAgICAgICAgICAgICAgIFJlYWxlOjxicj4NCiAgICAg
        ICAgICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgICAgICAgICANCiAg
        ICAgICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgIC0tDQogICAgICAgICAgICAgICAgICAgICAgICANCiAgICAgICAg
        ICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgPC9kaXY+DQoNCgkJCQk8
        IS0tIFVMVElNQSBGRVJNQVRBIC0tPg0KCQkJCQ0KDQoJCQkJPCEtLSBMSU5L
        IERFVFRBR0xJTyBGRVJNQVRFIC0tPg0KCQkJCQ0KCQkJCQk8ZGl2IGNsYXNz
        PSJldmlkZW56aWF0byI+DQogICAgICAgICAgICAgICAgICAgICAgICANCiAg
        ICAgICAgICAgICAgICAgICAgICAgIDxhIGhyZWY9Ii92dF9wYXhfaW50ZXJu
        ZXQvbW9iaWxlL3NjaGVkYT9kZXR0YWdsaW89dmlzdWFsaXp6YSZudW1lcm9U
        cmVubz0yNTcyJmNvZExvY09yaWc9JnRpcG9SaWNlcmNhPW51bWVybyZsYW5n
        PUlUIj7CuyBWZWRpIGRldHRhZ2xpbyBmZXJtYXRlPC9hPg0KCQkJCQk8L2Rp
        dj4NCgkJCQkNCg0KICAgICAgICAgICAgICAgIDwhLS0gREVTVElOQVpJT05F
        IC0tPg0KCQkJCTxkaXYgY2xhc3M9ImNvcnBvY2VudHJhbGUiPg0KCQkJCQk8
        aDI+VElSQU5PPC9oMj4NCgkJCQkJPHA+QXJyaXZvIFByb2dyYW1tYXRvOjxi
        ci8+DQoJCQkJCSAgICA8c3Ryb25nPg0KICAgICAgICAgICAgICAgICAgICAg
        ICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAyMDo1
        Mg0KICAgICAgICAgICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAg
        ICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAgICAgICAg
        ICAgICANCiAgICAgICAgICAgICAgICAgICAgICAgICAgICANCiAgICAgICAg
        ICAgICAgICAgICAgICAgIDwvc3Ryb25nPg0KCQkJCQk8L3A+DQoJCQkJCTxw
        Pg0KCQkJCQkNCgkJCQkJCQ0KCQkJCQkJDQoJCQkJCQkJQXJyaXZvIHByZXZp
        c3RvOjxici8+DQoJCQkJCQkJPHN0cm9uZz4yMDo1Mjwvc3Ryb25nPg0KCQkJ
        CQkJDQoJCQkJCQ0KCQkJCQk8L3A+DQoNCiAgICAgICAgICAgICAgICAgICAg
        QmluYXJpbw0KICAgICAgICAgICAgICAgICAgICBQcmV2aXN0bzo8YnI+DQog
        ICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAgICAg
        DQogICAgICAgICAgICAgICAgICAgICAgICANCiAgICAgICAgICAgICAgICAg
        ICAgICAgICAgICANCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
        DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgMiAg
        ICAgICAgICAgICAgDQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
        ICAgICANCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAN
        CiAgICAgICAgICAgICAgICAgICAgICAgICAgICANCiAgICAgICAgICAgICAg
        ICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICANCiAgICAgICAgICAg
        ICAgICAgICAgPGJyPg0KICAgICAgICAgICAgICAgICAgICBCaW5hcmlvDQog
        ICAgICAgICAgICAgICAgICAgIFJlYWxlOjxicj4NCiAgICAgICAgICAgICAg
        ICAgICAgDQogICAgICAgICAgICAgICAgICAgICAgICANCiAgICAgICAgICAg
        ICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAgICAgICAgICAgLS0N
        CiAgICAgICAgICAgICAgICAgICAgICAgIA0KICAgICAgICAgICAgICAgICAg
        ICANCiAgICAgICAgICAgICAgICA8L2Rpdj4NCgkJDQoJCQkJPCEtLSBTSVRV
        QVpJT05FIC0tPg0KCQkJCTxkaXYgIGNsYXNzPSJldmlkZW56aWF0byI+PHN0
        cm9uZz4NCgkJCQlJbCB0cmVubw0KCQkJCQ0KCQkJCQlub24gZSYjMDM5OyBh
        bmNvcmEgcGFydGl0bw0KCQkJCQkNCgkJCQkJDQoJCQkJDQogICAgICAgICAg
        ICAgICAgPGJyPg0KICAgICAgICAgICAgICAgICA8IS0tYzppZiB0ZXN0PSIk
        eyFlbXB0eSBhbmRhbWVudG8uc3RhemlvbmVVbHRpbW9SaWxldmFtZW50byAm
        JiAhIGVtcHR5IGFuZGFtZW50by5vcmFVbHRpbW9SaWxldmFtZW50byAmJiBl
        bXB0eSBhcnJpdm8uZWZmZXR0aXZhfSItLT4NCiAgICAgICAgICAgICAgICAN
        Cg0KICAgICAgICAgICAgICAgIDwvc3Ryb25nPjxicj4NCiAgICAgICAgICAg
        ICAgICA8L2Rpdj4NCgkJCQ0KCQkNCgkJDQoJCTwhLS0gRk9PVEVSICsgTElO
        SyAtLT4NCgkJPGRpdiBpZD0iZm9vdGVyIj4NCgkJCQ0KCQkJCQ0KCQkJCQ0K
        CQkJCQk8YSBocmVmPSIvdnRfcGF4X2ludGVybmV0L21vYmlsZS9udW1lcm8/
        bGFuZz1JVCI+wrsgTnVvdmEgcmljZXJjYSA8L2E+PGJyLz4NCiAgICAgICAg
        ICAgICAgICAgICAgPGEgaHJlZj0iL3Z0X3BheF9pbnRlcm5ldC9tb2JpbGUv
        c3RhemlvbmU/bGFuZz1JVCI+wrsgQ2VyY2EgcGVyIHN0YXppb25lPC9hPg0K
        ICAgICAgICAgICAgICAgICAgICA8YSBocmVmPSIvdnRfcGF4X2ludGVybmV0
        L21vYmlsZS90cmFnaXR0bz9sYW5nPUlUIj7CuyBDZXJjYSBwZXIgZGF0aSBk
        aSB2aWFnZ2lvPC9hPjxici8+DQogICAgICAgICAgICAgICAgDQogICAgICAg
        ICAgICAgICAgDQogICAgICAgICAgICANCiAgICAgICAgICAgIDxicj4NCg0K
        ICAgICAgICAgICAgPHA+PGltZyBzcmM9Ii92dF9wYXhfaW50ZXJuZXQvaW1h
        Z2VzL2ljb25hUmljZXJjYS5wbmciIHN0eWxlPSJ2ZXJ0aWNhbC1hbGlnbjog
        bWlkZGxlOyIvPg0KICAgICAgICAgICAgICAgIDxhIGhyZWY9Ii92dF9wYXhf
        aW50ZXJuZXQvbW9iaWxlL3Byb2dyYW1tYXRvP2xhbmc9SVQiPk9yYXJpbyBU
        cmVuaTwvYT4NCiAgICAgICAgICAgIDwvcD4NCiAgICAgICAgICAgIDxwIGlk
        PSJjb3B5bm90ZSI+Q29weXJpZ2h0IFRyZW5pdGFsaWEgUy5wLkEuIDIwMDYu
        PGJyIC8+VHV0dGkgaSBkaXJpdHRpIHJpc2VydmF0aS48L3A+DQoJCTwvZGl2
        Pg0KDQoJPC9ib2R5Pg0KPC9odG1sPg0K
    http_version: 
  recorded_at: Thu, 14 Jan 2016 15:34:06 GMT
recorded_with: VCR 3.0.1
